import * as THREE from 'three';
import {World} from '../src/world';
import {LevelEditor} from '../src/editor';
import {BUILTIN_DOCUMENTS,cloneDocument,packageLevel,parsePackage} from '../src/level-document';
import {newSkyBody,newPlanetRing,newCorona,minimumSkyDistance,themeLighting} from '../src/lighting';
import {THEMES} from '../src/themes';
import {newSculpt} from '../src/sculpt';
import {gameCameraQuaternion} from '../src/game-camera';
import {saveLevel,savedLevels} from '../src/level-storage';

const output=document.querySelector<HTMLElement>('#results')!,button=document.querySelector<HTMLButtonElement>('#run')!;
const world=new World(document.querySelector<HTMLElement>('#viewport')!),editor=new LevelEditor(world,{play:()=>{},close:()=>{},changed:()=>{}}),api=editor as any;
const frame=()=>new Promise<void>(r=>requestAnimationFrame(()=>r()));
function render(){if(editor.active)editor.render();requestAnimationFrame(render);}requestAnimationFrame(render);
const check=(ok:unknown,label:string)=>{if(!ok)throw Error(label);output.textContent+='\nPASS '+label;};
const click=(selector:string)=>{const el=document.querySelector<HTMLButtonElement>(selector);if(!el)throw Error('Missing '+selector);el.click();};
function field(key:string,value:string){const el=document.querySelector<HTMLInputElement>('[data-light-field="'+key+'"]')!;el.value=value;el.dispatchEvent(new Event('change',{bubbles:true}));}
function pointer(type:string,p:{x:number;y:number}){world.renderer.domElement.dispatchEvent(new PointerEvent(type,{clientX:p.x,clientY:p.y,pointerId:88,button:0,buttons:type==='pointerup'?0:1,bubbles:true,cancelable:true}));}
function selected(){return editor.document.lighting!.bodies.find(b=>b.id===editor.selection)!;}
function ringPoint(axis:number,index:number){return api.skyView.screen(api.skyView.ringPaths[axis][index].clone().multiplyScalar(api.skyView.ringHandles.scale.x).add(api.skyView.ringHandles.position));}
async function measure(label:string){for(let i=0;i<15;i++)await frame();const samples:number[]=[];for(let i=0;i<90;i++){const start=performance.now();await frame();samples.push(performance.now()-start);}samples.sort((a,b)=>a-b);output.textContent+='\nFRAME '+JSON.stringify({label,width:innerWidth,height:innerHeight,medianMs:samples[45],p95Ms:samples[85],drawCalls:world.renderer.info.render.calls,triangles:world.renderer.info.render.triangles,particles:world.lighting.ringParticles.count,memory:world.renderer.info.memory});}
document.querySelector<HTMLButtonElement>('#hide')!.onclick=()=>document.querySelector<HTMLElement>('#test-controls')!.hidden=true;
world.ready.then(()=>button.disabled=false);
button.onclick=async()=>{button.disabled=true;output.textContent='Celestial integration';try{
  const doc=cloneDocument(BUILTIN_DOCUMENTS[1]);doc.id='celestial-qa-'+crypto.randomUUID();doc.name='Saturnring · Lichtwerkstatt';doc.objects=doc.objects.slice(0,3).map((o,i)=>({...o,x:[0,-70,78][i],z:[-18,-48,-62][i],scale:[.8,.6,.65][i],parameters:{sculptId:'test-rock-'+i}}));doc.sculpts=Object.fromEntries(doc.objects.map((o,i)=>['test-rock-'+i,newSculpt('test-rock-'+i,(['block','split','slab'] as const)[i])]));doc.deposits=[];doc.delivery={ferrite:0,copper:0,crystal:0};doc.spawn={x:52,z:35};doc.base.x=-90;doc.base.z=55;
  doc.lighting=themeLighting(THEMES.belt);const planet=newSkyBody('saturn','planet');Object.assign(planet,{surface:'gas',azimuth:-105,elevation:-36,distance:600,size:32,illuminates:false,color:'#dccdac',ring:{...newPlanetRing(),enabled:true,density:1,opacity:.85,orientation:new THREE.Quaternion().setFromEuler(new THREE.Euler(THREE.MathUtils.degToRad(-36),0,THREE.MathUtils.degToRad(8))).toArray()}});
  const sun=newSkyBody('solar','sun');Object.assign(sun,{azimuth:-57,elevation:-36,size:9,distance:1000,intensity:1.8,corona:newCorona()});doc.lighting.bodies.push(planet,sun);
  await editor.open(doc);click('[data-light-select="saturn"]');editor.render();await frame();
  check(!!document.querySelector('#sky-game-angle')&&!!document.querySelector('#sky-preview'),'game angle and true game preview are exposed in the spatial toolbar');
  const original=JSON.stringify(editor.document);click('#sky-game-angle');editor.render();check(api.skyView.camera.quaternion.angleTo(gameCameraQuaternion())<1e-7&&JSON.stringify(editor.document)===original,'game angle matches gameplay without editing the level');
  field('distance','350');check(selected().distance===350,'planet can move well below the old 800 m limit');const near=JSON.stringify(editor.document);field('size','60');check(selected().distance===minimumSkyDistance(selected()),'enlarging a near body raises distance safely in the same edit');click('#editor-undo');check(JSON.stringify(editor.document)===near,'size and automatic distance correction undo together');click('#editor-redo');check(selected().size===60,'redo restores the safe large body');click('#editor-undo');field('distance','600');
  field('ring.angle.x','-25');check(Math.abs(new THREE.Euler().setFromQuaternion(new THREE.Quaternion().fromArray(selected().ring!.orientation)).x-THREE.MathUtils.degToRad(-25))<1e-8,'numeric ring tilt updates its quaternion');click('#editor-undo');
  const beforeRing=JSON.stringify(editor.document),host=world.editorObjects[0];click('#sky-ring-edit');click('#sky-ring-edit');check(!api.skyView.ringMode&&!api.skyView.ringHandles.visible,'the same properties button exits ring alignment');click('#sky-ring-edit');window.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));check(!api.skyView.ringMode&&api.skyMode,'Escape exits ring alignment without leaving the sky editor');click('#sky-ring-edit');editor.render();check(api.skyView.ringMode&&api.skyView.ringHandles.visible,'concentric three-axis rotation handles are visible');
  const start=ringPoint(1,12),end=ringPoint(1,20);pointer('pointerdown',start);check(api.skyView.gesture?.kind==='ring','rotation handle starts a ring gesture');pointer('pointermove',end);editor.render();check(JSON.stringify(editor.document)===beforeRing&&world.editorObjects[0]===host,'live ring rotation retains draft and world meshes');pointer('pointerup',end);const rotated=JSON.stringify(editor.document);check(rotated!==beforeRing,'ring gesture commits a changed orientation');click('#editor-undo');check(JSON.stringify(editor.document)===beforeRing,'ring drag is one global undo step');click('#editor-redo');check(JSON.stringify(editor.document)===rotated,'ring rotation redo restores exact data');
  editor.render();pointer('pointerdown',start);pointer('pointermove',end);window.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));pointer('pointerup',end);check(JSON.stringify(editor.document)===rotated&&!api.skyView.dragging,'Escape cancels an active ring gesture');
  editor.render();pointer('pointerdown',start);pointer('pointermove',end);pointer('pointercancel',end);check(JSON.stringify(editor.document)===rotated,'pointer cancellation restores ring data');click('#sky-ring-done');click('#editor-undo');
  click('#light-duplicate');const duplicate=selected(),copiedId=duplicate.id;check(duplicate.ring!==editor.document.lighting!.bodies.find(b=>b.id==='saturn')!.ring,'duplicating a planet deep-copies ring data');field('ring.outer','3.5');check(editor.document.lighting!.bodies.find(b=>b.id==='saturn')!.ring!.outer===2.8,'editing duplicated ring leaves original unchanged');click('#light-delete');check(!editor.document.lighting!.bodies.some(b=>b.id===copiedId),'duplicate can be removed independently');click('[data-light-select="saturn"]');click('#sky-game-angle');editor.render();
  const camera=api.skyView.camera.position.clone(),draft=JSON.stringify(editor.document),state=JSON.stringify(api.state);click('#sky-preview');editor.render();await frame();check(api.skyView.preview&&api.skyPreviewState.deployment===null,'preview shows the spawn without the arrival sequence');check(JSON.stringify(api.state)===state&&JSON.stringify(editor.document)===draft,'animated preview changes no expedition state or authored document');check(world.camera instanceof THREE.OrthographicCamera&&world.camera.quaternion.angleTo(gameCameraQuaternion())<1e-7,'preview uses the unchanged orthographic gameplay camera');
  const texture=(world as any).previewMaterial.uniforms.image.value;check(texture?.isTexture&&texture.image.width>=innerWidth,'preview uses a full-window postprocessed texture before letterboxing');
  pointer('pointerdown',{x:innerWidth/2,y:innerHeight/2});pointer('pointermove',{x:innerWidth/2+80,y:innerHeight/2});pointer('pointerup',{x:innerWidth/2+80,y:innerHeight/2});check(JSON.stringify(editor.document)===draft&&!api.skyView.dragging,'preview cannot accidentally move a sky object');
  const geometryMemory:number[]=[];for(let i=0;i<5;i++){click('#sky-preview');editor.render();click('#sky-preview');editor.render();await frame();geometryMemory.push(world.renderer.info.memory.geometries);}check(geometryMemory.at(-1)!<=geometryMemory[1]+1,'repeated overview / preview switches do not accumulate geometries');output.textContent+='\nMEMORY '+JSON.stringify(geometryMemory);
  await measure('High game preview');world.setQuality('standard');editor.render();check(world.lighting.ringParticles.count<=700,'Standard shares a 700-particle budget across rings');await measure('Standard game preview');world.setQuality('high');editor.render();check(world.lighting.ringParticles.count<=2000,'High shares a 2000-particle budget across rings');
  click('#sky-preview');editor.render();check(api.skyView.camera.position.distanceTo(camera)<1e-8,'returning from preview restores overview framing');click('[data-light-select="solar"]');field('corona.strength','2.2');field('corona.extent','.8');field('corona.motion','.7');editor.render();check(selected().intensity===1.8,'corona controls do not change global lighting strength');
  const solar=api.skyView.bodies.get('solar'),u=solar.children[2].material.uniforms;check(u.extent.value===.8&&u.power.value===2.2,'shared editor shader receives corona controls');world.setQuality('standard');editor.render();check(u.detail.value===2,'standard editor reduces prominence arcs');world.setQuality('high');editor.render();check(u.detail.value===4,'high editor restores full prominence detail');
  const pack=packageLevel(editor.document);await saveLevel(pack);const loaded=(await savedLevels()).find(p=>p.level.id===editor.document.id)!;check(JSON.stringify(loaded.level)===JSON.stringify(editor.document)&&JSON.stringify(parsePackage(JSON.stringify(pack)).level)===JSON.stringify(editor.document),'ring and corona persist exactly through IndexedDB and JSON');
  const beforePlay=JSON.stringify(editor.document);click('#editor-play');api.returnFromTest();editor.render();check(api.skyMode&&JSON.stringify(editor.document)===beforePlay,'full play return preserves celestial draft and view');
  check(!world.renderer.info.programs?.some((p:any)=>p.diagnostics&&!p.diagnostics.runnable),'solar, ring and particle shaders compile on real WebGL');
  await editor.open(BUILTIN_DOCUMENTS[0]);click('[data-light-select="sky-main"]');click('#sky-preview');editor.render();check(api.skyView.preview&&api.skyPreviewState.environment.kind==='planet','Aster supports the same stationary game preview');
  await editor.open(loaded.level);click('[data-light-select="saturn"]');click('#sky-game-angle');click('#sky-preview');editor.render();output.textContent+='\nALL CELESTIAL CHECKS PASSED';
}catch(e){output.textContent+='\nFAIL '+String(e);console.error(e);}finally{if(api.saveTimer)clearTimeout(api.saveTimer);button.disabled=false;}};
