import * as THREE from 'three';
import {World} from '../src/world';
import {LevelEditor} from '../src/editor';
import {cloneDocument,BUILTIN_DOCUMENTS,packageLevel,parsePackage} from '../src/level-document';
import {saveLevel,savedLevels} from '../src/level-storage';
import {SnapshotWriter} from '../src/snapshot-writer';
import {getLevelWorld} from '../src/levels';
const world=new World(document.querySelector<HTMLElement>('#viewport')!),editor=new LevelEditor(world,{play:()=>{},close:()=>{},changed:()=>{}}),api=editor as any;
const run=document.querySelector<HTMLButtonElement>('#run')!,output=document.querySelector<HTMLElement>('#results')!;
const frame=()=>new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));
const check=(ok:unknown,label:string)=>{if(!ok)throw Error(label);output.textContent+='\nPASS '+label;};
const pointer=(type:string,p:{x:number;y:number},extra:PointerEventInit={})=>world.renderer.domElement.dispatchEvent(new PointerEvent(type,{clientX:p.x,clientY:p.y,pointerId:91,button:0,buttons:type==='pointerup'?0:1,bubbles:true,...extra}));
function screen(x:number,y:number,z:number){const p=new THREE.Vector3(x,y,z).project(world.camera),r=world.renderer.domElement.getBoundingClientRect();return {x:r.left+(p.x+1)*r.width/2,y:r.top+(1-p.y)*r.height/2};}
async function ready(){await editor.whenReady();while(api.sculptBusy||api.workerInFlight||api.strokeQueue.length)await frame();}
function render(){if(editor.active)editor.render();requestAnimationFrame(render);}requestAnimationFrame(render);
world.ready.then(()=>run.disabled=false);document.querySelector<HTMLButtonElement>('#hide')!.onclick=()=>document.querySelector<HTMLElement>('#test-panel')!.hidden=true;
run.onclick=async()=>{run.disabled=true;output.textContent='Real-time editor integration';try{
  const doc=cloneDocument(BUILTIN_DOCUMENTS[1]);doc.id='realtime-qa-'+crypto.randomUUID();doc.name='Echtzeit · Werkstatt';await editor.open(doc);editor.render();const object=editor.document.objects[0],mesh=world.editorObjects.find(m=>m.userData.structure.id===object.id)!,geometry=mesh.geometry,material=mesh.material,other=world.editorObjects[1],otherGeometry=other.geometry,root=mesh.parent;
  const p=screen(object.x,0,object.z),end=screen(object.x+12,0,object.z+8),before=JSON.stringify(editor.document),start=performance.now();pointer('pointerdown',p);pointer('pointermove',end);check(mesh.position.x!==object.x,'the actual asteroid moves before pointer release');check(JSON.stringify(editor.document)===before,'drag preview leaves the authoring document unchanged');check(mesh.geometry===geometry&&mesh.material===material,'drag reuses rock geometry and material');pointer('pointerup',end);const dragMs=performance.now()-start;check(editor.pendingWorld,'collision and route validation run in the background');await ready();check(mesh===world.editorObjects.find(m=>m.userData.structure.id===object.id)&&mesh.geometry===geometry&&mesh.parent===root,'committing a transform retains the object and scene root');check(other===world.editorObjects[1]&&other.geometry===otherGeometry,'unaffected objects retain their GPU buffers');
  const moved={...editor.document.objects[0]};editor.render();const p2=screen(moved.x,0,moved.z),e2=screen(moved.x+10,0,moved.z);pointer('pointerdown',p2);pointer('pointermove',e2);world.renderer.domElement.dispatchEvent(new PointerEvent('pointercancel',{pointerId:91,bubbles:true}));await ready();check(mesh.position.x===moved.x&&mesh.position.z===moved.z,'cancel restores the live object and attached ores');
  const placeStart=performance.now();api.place('shape:block',55,90);const placed=editor.document.objects.at(-1)!,proxy=world.editorObjects.find(m=>m.userData.structure.id===placed.id);const placeMs=performance.now()-placeStart;check(!!proxy&&proxy.geometry.getAttribute('position').count>0,'a new asteroid has a rendered silhouette immediately');check(editor.pendingWorld,'placement detail and validation are asynchronous');await ready();check(world.editorObjects.find(m=>m.userData.structure.id===placed.id)===proxy&&!proxy!.userData.pending,'prepared geometry replaces the proxy without replacing the object');api.undo();await ready();check(!world.editorObjects.some(m=>m.userData.structure.id===placed.id),'undo removes the placement');api.redo();await ready();check(world.editorObjects.some(m=>m.userData.structure.id===placed.id),'redo restores the independent object');
  api.history.current.selection=placed.id;api.enterSculpt();await ready();editor.render();const sculptMesh=world.editorObjects.find(m=>m.userData.structure.id===placed.id)!,brush=screen(placed.x+10,11,placed.z+21),strokeStart=editor.document.sculpts![String(placed.parameters.sculptId)].strokes.length;api.brush.tool='subtract';pointer('pointerdown',brush);for(let i=0;i<12;i++)await frame();const releaseStart=performance.now();pointer('pointerup',brush);const releaseMs=performance.now()-releaseStart;check(!api.sculptBusy&&!api.finishRequested,'releasing the brush unlocks editing immediately');check(editor.document.sculpts![String(placed.parameters.sculptId)].strokes.length>strokeStart,'stroke commits to the document before background finalization');pointer('pointerdown',brush);check(!!api.workingSource,'another stroke can begin before the world has finished rebuilding');for(let i=0;i<8;i++)await frame();pointer('pointerup',brush);await ready();check(sculptMesh===world.editorObjects.find(m=>m.userData.structure.id===placed.id)&&other.geometry===otherGeometry,'multiple strokes preserve all unaffected scene buffers');check(getLevelWorld(doc.id).revision===world.levelWorld.revision,'latest cooked collision revision is installed');
  api.undo();await ready();const undone=editor.document.sculpts![String(placed.parameters.sculptId)].strokes.length;api.redo();await ready();check(editor.document.sculpts![String(placed.parameters.sculptId)].strokes.length>undone,'separate rapid strokes retain separate undo steps');
  api.leaveSculpt();await ready();api.history.current.selection=null;api.change((d:any)=>d.name='Background focus');const name=document.querySelector<HTMLInputElement>('#editor-name')!;name.focus();await ready();check(document.activeElement===name&&document.querySelector('#editor-name')===name,'background completion preserves the focused property input');
  const count=editor.document.objects.length;api.generator.autoSeed=false;api.generator.seed=8723;api.generate('form',{x:-85,z:105});const job=api.generation;check(!!world.editorObjects.find(m=>m.userData.structure.id===job.object.id)&&!api.sculptBusy,'generation immediately displays a proxy without locking the editor');const originalOther=editor.document.objects[1];api.change((d:any)=>d.objects[1].x+=4);const editedX=originalOther.x+4;while(api.generation)await frame();await ready();check(editor.document.objects.length===count+1&&editor.document.objects[1].x===editedX,'generation preserves concurrent edits to other objects');api.undo();await ready();check(editor.document.objects.length===count&&editor.document.objects[1].x===editedX,'generated placement has its own undo step');
  api.generate('form',{x:-100,z:90});const cancelled=api.generation.object.id;api.cancelGeneration();for(let i=0;i<5;i++)await frame();check(!world.editorObjects.some(m=>m.userData.structure.id===cancelled)&&editor.document.objects.length===count,'cancelled generation removes its proxy and ignores late results');
  const stable=world.renderer.info.memory.geometries;for(let i=0;i<3;i++){api.place('shape:slab',110+i*15,100);await ready();api.undo();await ready();await frame();}check(world.renderer.info.memory.geometries<=stable+2,'repeated placement and undo release temporary GPU geometry');
  api.lightChange((d:any)=>d.lighting.bodies[0].intensity=1.71);api.issues=[];api.play();check(editor.testing&&getLevelWorld(doc.id).lighting.bodies[0].intensity===1.71,'play uses the latest lighting without recompiling geometry');api.returnFromTest();await ready();
  await editor.persist();const persisted=(await savedLevels()).find(p=>p.level.id===doc.id)!;check(JSON.stringify(persisted.level)===JSON.stringify(editor.document),'real storage worker persists the current complete document');
  const writer=api.writer,writes:string[]=[];api.writer=new SnapshotWriter<any>(async pack=>{writes.push(pack.level.name);await new Promise(r=>setTimeout(r,200));await saveLevel(pack);});api.change((d:any)=>d.name='First save');const saving=editor.persist();api.change((d:any)=>d.name='Intermediate save');const middle=editor.persist();api.change((d:any)=>d.name='Latest save');const latest=editor.persist();check(editor.document.name==='Latest save'&&writes.length===1,'editing continues while a delayed write is in progress');await Promise.all([saving,middle,latest]);check(writes.join('|')==='First save|Latest save','waiting saves are coalesced to the newest revision');await ready();api.writer=writer;const final=(await savedLevels()).find(p=>p.level.id===doc.id)!;check(final.level.name==='Latest save','an old completion never overwrites or acknowledges a newer draft');check(JSON.stringify(parsePackage(JSON.stringify(packageLevel(editor.document))).level)===JSON.stringify(editor.document),'JSON still round trips every local form');
  output.textContent+='\nTIMING '+JSON.stringify({dragCommitMs:dragMs,placePreviewMs:placeMs,brushReleaseMs:releaseMs,calls:world.renderer.info.render.calls,memory:world.renderer.info.memory});check(!world.renderer.info.programs?.some((p:any)=>p.diagnostics&&!p.diagnostics.runnable),'incremental preview shaders compile');output.textContent+='\nALL REALTIME CHECKS PASSED';
}catch(error){output.textContent+='\nFAIL '+String(error);console.error(error);}finally{run.disabled=false;}};
