import * as THREE from 'three';
import {LAMP_NAMES,newLamp,newSkyBody,newRockGlow,newCorona,newPlanetRing,newAtmosphere,minimumSkyDistance,type LampKind,type SkyBody} from './lighting';
import type {LevelDocument} from './level-document';
import type {SculptDefinition} from './sculpt';
const esc=(s:unknown)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const number=(label:string,key:string,value:number,min:number,max:number,step:number|string=1)=>`<label>${label}<input aria-label="${label}" data-light-field="${key}" type="number" min="${min}" max="${max}" step="${step}" value="${Math.round(value*1000)/1000}"></label>`;
const color=(label:string,key:string,value:string)=>`<label>${label}<input aria-label="${label}" data-light-field="${key}" type="color" value="${value}"></label>`;
const bool=(label:string,key:string,value:boolean)=>`<label><span><input data-light-field="${key}" type="checkbox" ${value?'checked':''}> ${label}</span></label>`;
export function lightingPalette(d:LevelDocument,selection:string|null,sky:boolean){return `<h3>Himmel & Licht</h3><button id="editor-sky">${sky?'↩ Zur Levelansicht':'☀ Himmelsansicht'}</button><div class="editor-palette"><button data-add-sky="sun">＋ Sonne</button><button data-add-sky="planet">＋ Planet</button>${Object.entries(LAMP_NAMES).map(([kind,name])=>`<button data-add-lamp="${kind}">＋ ${name}</button>`).join('')}</div><div class="editor-objects">${[...(d.lighting?.bodies??[]).map(b=>({id:b.id,name:(b.kind==='sun'?'☀ ':'◉ ')+b.name})),...(d.lighting?.lamps??[]).map(l=>({id:l.id,name:'◈ '+LAMP_NAMES[l.kind]}))].map(o=>`<button data-light-select="${esc(o.id)}" aria-pressed="${selection===o.id}">${esc(o.name)}</button>`).join('')}</div>`;}
export function lightProperties(d:LevelDocument,id:string|null,ringMode=false){
  const l=d.lighting!,body=l.bodies.find(b=>b.id===id),lamp=l.lamps.find(p=>p.id===id);if(!body&&!lamp)return '';
  const actions='<div class="editor-actions"><button id="light-duplicate">Licht duplizieren</button><button id="light-delete">Licht löschen</button></div>';
  if(body){const corona=body.corona??newCorona(),air=body.air??newAtmosphere(),ring=body.ring??newPlanetRing(),angles=new THREE.Euler().setFromQuaternion(new THREE.Quaternion().fromArray(ring.orientation));
    const surface=body.kind==='sun'?`<details open><summary>Feurige Korona</summary>${number('Flammenausdehnung','corona.extent',corona.extent,.1,2,.05)}${number('Koronastärke','corona.strength',corona.strength,0,5,.1)}${number('Plasmabewegung','corona.motion',corona.motion,0,3,.05)}</details>`:`<details open><summary>Planetenatmosphäre</summary>${number('Atmosphärenhöhe · % des Radius','air.extent',air.extent*100,.5,50,.5)}${number('Atmosphärenstärke','air.strength',air.strength,0,5,.1)}${color('Atmosphärenfarbe','air.color',air.color)}<p class="editor-note">Weiche Streuung und beleuchteter Rand. Die Höhe verändert die Hülle, unabhängig von Planetengröße und Lichtstärke.</p></details><label>Oberfläche<select data-light-field="surface">${[['rocky','Felsplanet'],['ocean','Ozeanplanet'],['gas','Gasriese']].map(([v,n])=>`<option value="${v}" ${body.surface===v?'selected':''}>${n}</option>`).join('')}</select></label><details open><summary>Planetenring</summary>${bool('Ring aktivieren','ring.enabled',ring.enabled)}${ring.enabled?`${number('Innenradius · Planetenradien','ring.inner',ring.inner,1.05,19,.05)}${number('Außenradius · Planetenradien','ring.outer',ring.outer,1.1,20,.05)}${color('Ringfarbe','ring.color',ring.color)}${number('Ringdeckkraft','ring.opacity',ring.opacity,0,1,.05)}${number('Staub & Eisdichte','ring.density',ring.density,0,1,.05)}${['x','y','z'].map(a=>number('Ringwinkel '+a.toUpperCase()+' · °','ring.angle.'+a,THREE.MathUtils.radToDeg(angles[a as 'x'|'y'|'z']),-180,180,'any')).join('')}<button id="sky-ring-edit" aria-pressed="${ringMode}">${ringMode?'✓ Ringausrichtung beenden':'◌ Ring interaktiv ausrichten'}</button><p class="editor-note">Farbige Drehgriffe kippen den Ring um das Planetenzentrum. Nahe Fels- und Eisbrocken liegen auf derselben Ringebene.</p>`:''}</details>`;
    return `<h3>${body.kind==='sun'?'Sonne':'Planet'}</h3><label>Name<input data-light-field="name" maxlength="100" value="${esc(body.name)}"></label>${bool('Im Spiel sichtbar','visible',body.visible)}${bool('Beleuchtet Szene','illuminates',body.illuminates)}${bool('Hauptlicht mit Schatten','primary',l.primary===body.id)}${number('Himmelsrichtung °','azimuth',body.azimuth,-180,180,'any')}${number('Himmelshöhe °','elevation',body.elevation,-90,90,'any')}${number('Größe bei 1.000 m · °','size',body.size,1,70)}${number('Abstand · m','distance',body.distance??1000,Math.floor(minimumSkyDistance(body)*1000)/1000,20000,'any')}${color('Lichtfarbe','color',body.color)}${number('Globale Lichtstärke','intensity',body.intensity,0,10,.1)}${bool(body.kind==='sun'?'Korona':'Atmosphärenrand','atmosphere',body.atmosphere)}${surface}${actions}<p class="editor-note">Körper auf der Halbkugel ziehen. Der goldene Griff verändert den Abstand. Größe und globale Lichtstärke bleiben separat einstellbar.</p>`;
  }
  const p=lamp!;return `<h3>${LAMP_NAMES[p.kind]}</h3>${number('Lichtposition X','x',p.x,-400,400,.5)}${number('Lichtposition Z','z',p.z,-400,400,.5)}${number('Höhe über Ebene','height',p.height,0,100,.5)}${color('Lichtfarbe','color',p.color)}${number('Lokale Lichtstärke','intensity',p.intensity,0,2000,10)}${number('Lichtreichweite','range',p.range,1,150)}${p.kind==='floodlight'?number('Ausrichtung °','azimuth',p.azimuth,-180,180)+number('Neigung °','elevation',p.elevation,-90,90)+number('Lichtkegel °','angle',p.angle,5,85):''}<label>Lichtverlauf<select data-light-field="pattern">${[['steady','Dauerlicht'],['pulse','Pulsieren'],['flicker','Flackern']].map(([v,n])=>`<option value="${v}" ${p.pattern===v?'selected':''}>${n}</option>`).join('')}</select></label>${actions}<p class="editor-note">Lampe im Flugraum ziehen. Höhe wird relativ zu Gelände oder Flugebene gespeichert.</p>`;
}
export function glowProperties(s:SculptDefinition){const g=s.glow??newRockGlow();const input=(label:string,key:string,value:number,min:number,max:number,step=.1)=>number(label,key,value,min,max,step).replaceAll('data-light-field','data-glow-field');const colour=(label:string,key:string,v:string)=>color(label,key,v).replaceAll('data-light-field','data-glow-field');
  return `<details open><summary>Leuchtendes Gestein</summary><p class="editor-note">Form bearbeiten → Oberfläche malen → Leuchten. Strg entfernt Leuchten.</p>${colour('Oberflächenleuchten','color',g.color)}${input('Leuchtstärke','intensity',g.intensity,0,20)}${input('Spalten betonen','cracks',g.cracks,0,1,.05)}${bool('Inneren Leuchtbereich aktivieren','core.enabled',g.core.enabled).replaceAll('data-light-field','data-glow-field')}${colour('Farbe des Inneren','core.color',g.core.color)}${input('Stärke des Inneren','core.intensity',g.core.intensity,0,20)}<div class="editor-pair">${['X','Y','Z'].map((a,i)=>input('Kernzentrum '+a,'core.center.'+i,g.core.center[i],-36,36,.5)+input('Kernradius '+a,'core.radii.'+i,g.core.radii[i],1,36,.5)).join('')}</div>${input('Weicher Kernrand','core.softness',g.core.softness,.01,1,.01)}</details>`;
}
export function skyOverlay(d:LevelDocument,selection:string|null,side:1|-1,preview=false,ringMode=false){return `<section class="editor-sky ${preview?'sky-preview':''}" aria-label="Räumliche Himmelsansicht"><div class="sky-toolbar"><strong>${preview?'Spielvorschau · Startpunkt':'Himmelsansicht · 3D'}</strong><div class="editor-actions"><button id="sky-game-angle" ${preview?'disabled':''}>Spielwinkel</button><button id="sky-preview" aria-pressed="${preview}">${preview?'↩ Zur Himmelsansicht':'Spielvorschau'}</button>${preview?'':`<button id="sky-upper" title="Ausgewählten Körper nach oben spiegeln" aria-pressed="${side===1}">Oben</button><button id="sky-lower" title="Ausgewählten Körper nach unten spiegeln" aria-pressed="${side===-1}">Unten</button><button id="sky-fit">Ansicht einpassen</button>${ringMode?'<button id="sky-ring-done">✓ Ringausrichtung beenden</button>':''}`}</div><span>${preview?'Spielkamera und Beleuchtung · Entwurf bleibt unverändert':`${side===1?'Über':'Unter'} dem Horizont · Abstand <output id="sky-distance-readout"></output>`}</span></div>${preview?'':`<div id="sky-labels"></div><span class="sky-helper-label" id="sky-handle-label">↔ Abstand ziehen</span><span class="sky-helper-label sky-level-label" id="sky-origin-label">Level · Horizont</span><span class="sky-helper-label sky-level-label" id="sky-atlas-label">ATLAS</span><span class="sky-helper-label sky-level-label" id="sky-spawn-label">Start</span>`}<p class="sky-help">${preview?'Keine Simulation · Esc: zurück zur Himmelsansicht':ringMode?'Rot / Grün / Blau: Ring um X / Y / Z drehen · Esc: abbrechen':'Körper ziehen: Richtung & Höhe · Goldener Griff: Abstand'}${preview?'':'<br>Alt + Links: drehen · Mitte: verschieben · Mausrad: Zoom'}</p></section>`;}
export interface LightEditorContext {document:LevelDocument;selection:string|null;sky:boolean;change:(f:(d:LevelDocument)=>void)=>void;select:(id:string,sky?:boolean)=>void;toggleSky:()=>void;placeLamp:(kind:LampKind)=>void;error:(message:string)=>void}
export function bindLightEditor(root:HTMLElement,c:LightEditorContext){
  root.querySelector('#editor-sky')?.addEventListener('click',c.toggleSky);
  root.querySelectorAll<HTMLElement>('[data-light-select]').forEach(b=>b.onclick=()=>c.select(b.dataset.lightSelect!,c.document.lighting!.bodies.some(o=>o.id===b.dataset.lightSelect)));
  root.querySelectorAll<HTMLElement>('[data-add-lamp]').forEach(b=>b.onclick=()=>c.placeLamp(b.dataset.addLamp as LampKind));
  root.querySelectorAll<HTMLElement>('[data-add-sky]').forEach(b=>b.onclick=()=>{const body=newSkyBody('sky-'+crypto.randomUUID(),b.dataset.addSky as SkyBody['kind']);if(c.document.lighting!.bodies.length>=16){c.error('Höchstens 16 Himmelskörper.');return;}if(c.document.lighting!.bodies.filter(b=>b.illuminates).length>=4)body.illuminates=false;c.change(d=>d.lighting!.bodies.push(body));c.select(body.id,true);});
  root.querySelectorAll<HTMLInputElement|HTMLSelectElement>('[data-light-field]').forEach(input=>input.onchange=()=>{
    if(!input.checkValidity())return;const key=input.dataset.lightField!,v=input instanceof HTMLInputElement&&input.type==='checkbox'?input.checked:input instanceof HTMLInputElement&&input.type==='number'?input.valueAsNumber:input.value;
    if(key==='illuminates'&&v&&c.document.lighting!.bodies.filter(b=>b.illuminates).length>=4){c.error('Höchstens vier aktive Himmelslichter.');(input as HTMLInputElement).checked=false;return;}
    c.change(d=>{const l=d.lighting!,body=l.bodies.find(b=>b.id===c.selection),target=body??l.lamps.find(p=>p.id===c.selection);if(!target)return;if(key==='primary'){l.primary=v?target.id:null;if(body&&v)body.illuminates=true;}else if(body&&key.startsWith('air.')){body.air??=newAtmosphere();(body.air as any)[key.slice(4)]=key==='air.extent'?(v as number)/100:v;}else if(body&&key.startsWith('corona.')){body.corona??=newCorona();(body.corona as any)[key.slice(7)]=v;}else if(body&&key.startsWith('ring.')){body.ring??=newPlanetRing();if(key.startsWith('ring.angle.')){const angles=new THREE.Euler().setFromQuaternion(new THREE.Quaternion().fromArray(body.ring.orientation));angles[key.slice(11) as 'x'|'y'|'z']=THREE.MathUtils.degToRad(v as number);body.ring.orientation=new THREE.Quaternion().setFromEuler(angles).toArray() as [number,number,number,number];}else (body.ring as any)[key.slice(5)]=v;}else{(target as any)[key]=v;if(body&&key==='size')body.distance=Math.max(body.distance??1000,minimumSkyDistance(body));if(key==='illuminates'&&!v&&l.primary===target.id)l.primary=null;}});
  });
  root.querySelector('#light-delete')?.addEventListener('click',()=>c.change(d=>{const l=d.lighting!;l.bodies=l.bodies.filter(o=>o.id!==c.selection);l.lamps=l.lamps.filter(o=>o.id!==c.selection);if(l.primary===c.selection)l.primary=null;}));
  root.querySelector('#light-duplicate')?.addEventListener('click',()=>{let id='';c.change(d=>{const l=d.lighting!,b=l.bodies.find(b=>b.id===c.selection),p=l.lamps.find(p=>p.id===c.selection);id='light-'+crypto.randomUUID();if(b&&l.bodies.length<16)l.bodies.push({...structuredClone(b),id,name:b.name+' · Kopie',illuminates:false});else if(p&&l.lamps.length<96)l.lamps.push({...p,id,x:Math.min(400,p.x+5),z:Math.min(400,p.z+5)});});if(id)c.select(id,c.sky);});
  root.querySelectorAll<HTMLInputElement>('[data-glow-field]').forEach(input=>input.onchange=()=>{if(!input.checkValidity())return;c.change(d=>{const object=d.objects.find(o=>o.id===c.selection),s=object&&d.sculpts?.[String(object.parameters.sculptId)];if(!s)return;s.glow??=newRockGlow();const keys=input.dataset.glowField!.split('.');let target:any=s.glow;for(const k of keys.slice(0,-1))target=target[k];target[keys.at(-1)!]=input.type==='checkbox'?input.checked:input.type==='color'?input.value:input.valueAsNumber;});});
}
